services:
  sqs-admin-ui:
    image: akilamaxi/sqs-admin-ui:v1
    environment:
      - AWS_ACCESS_KEY_ID=X
      - AWS_SECRET_ACCESS_KEY=X
      - AWS_REGION=eu-west-2
      - SQS_ENDPOINT_URL=http://localstack:4566
    ports:
      - "5768:8080"
    networks:
      - orderflow-network

networks:
  orderflow-network:
    name: orderflow-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24