services:
  localstack:
    container_name: localstack
    image: localstack/localstack-pro
    ports:
      - 4566:4566
      - 4510-4559:4510-4559
    environment:
      DYNAMODB_SHARE_DB: 1
      LOCALSTACK_AUTH_TOKEN: "${LOCALSTACK_AUTH_TOKEN}"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4566/_localstack/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - "/var/lib/localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - orderflow-network
  
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - 2181:2181
    networks:
      - orderflow-network

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9991
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "kafka-topics --bootstrap-server localhost:9092 --list",
        ]
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    networks:
      - orderflow-network
  
  debezium:
    container_name: debezium
    image: debezium/connect:3.0.0.Final
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: "connect_configs"
      OFFSET_STORAGE_TOPIC: "connect_offsets"
    depends_on:
      kafka:
        condition: service_healthy
      localstack:
        condition: service_healthy
    ports:
      - 8083:8083
    networks:
      - orderflow-network
  
  schema-registry:
    container_name: schema-registry
    image: confluentinc/cp-schema-registry:latest
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:9092
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081, http://localhost:8081
    ports:
      - 8081:8081
    depends_on:
      - zookeeper
      - kafka
    networks:
      - orderflow-network
  
networks:
  orderflow-network:
    name: orderflow-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24