services:
  seq:
    container_name: "seq"
    image: datalust/seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5431:80"
    networks:
      - orderflow-network

networks:
  orderflow-network:
    name: orderflow-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24