services:
  orderflow:
    container_name: orderflow-api
    build:
      context: .
      dockerfile: ./src/OrderFlow.Api/Dockerfile
    
    ports:
      - "8080:8080"
    
    environment:
      - ASPNETCORE_ENVIRONMENT=Test