services:
  localstack:
    container_name: "localstack"
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - DYNAMODB_SHARE_DB=1
      
  postgres:
    container_name: "postgres"
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=Password1!
      - POSTGRES_USER=order_user
      - POSTGRES_DB=orderflow_db
