services:
  localstack:
    container_name: "localstack"
    image: localstack/localstack-pro
    ports:
      - "4566:4566"
    environment:
      - LOCALSTACK_AUTH_TOKEN="ls-CesAdave-vOQa-mEfO-6046-DebO68668892"
      - DYNAMODB_SHARE_DB=1
  
  seq:
    container_name: "seq"
    image: datalust/seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5431:80"