services:
  seq:
    container_name: "seq"
    image: datalust/seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5431:80"
    networks:
      - orderflow-network

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: unless-stopped
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    networks:
      - orderflow-network
  
  grafana:
    container_name: grafana
    image: grafana/grafana-oss
    volumes:
      - ./grafana-storage:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - orderflow-network
  
  networks:
    orderflow-network:
      name: orderflow-network
      driver: bridge
      ipam:
        config:
          - subnet: 172.16.0.0/24