global:
  scrape_interval: 15s
  evaluation_interval: 15s
  
alerting:
  alertmanagers: 
    - static_configs: 
        - targets: []

scrape_configs: 
  - job_name: 'prometheus'
    scrape_interval: 1s
    static_configs: 
      - targets: ['orderflow-api:8080']